components:
  schemas:
    EmotionRequest:
      properties:
        text:
          title: Text
          type: string
      required:
      - text
      title: EmotionRequest
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.1.0
paths:
  /:
    get:
      operationId: root__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Root
  /analyze_emotion:
    post:
      operationId: analyze_emotion_endpoint_analyze_emotion_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmotionRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Analyze Emotion Endpoint
  /analyze_gemini:
    post:
      operationId: analyze_gemini_endpoint_analyze_gemini_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmotionRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Analyze Gemini Endpoint
  /filtering_post:
    post:
      operationId: filtering_post_endpoint_filtering_post_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmotionRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Filtering Post Endpoint
  /gemini:
    post:
      operationId: responseGemini_endpoint_gemini_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmotionRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Responsegemini Endpoint
  /praise_response:
    post:
      operationId: response_praise_endpoint_praise_response_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmotionRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Response Praise Endpoint
  /scold_response:
    post:
      operationId: response_scold_endpoint_scold_response_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmotionRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Response Scold Endpoint
